server:
  servlet:
    context-path: /v1/card-ms/
  port: 8082

spring:
  application:
    name: spring-grpc-server-demo
  data:
    mongodb:
      port: 27017
      host: localhost
      username: admin
      password: password
      database: card_db
      auto-index-creation: true

grpc:
  port: 8085
  host: localhost