server:
  servlet:
    context-path: /v1/user-ms/
  port: 8081

spring:
  application:
    name: spring-grpc-client-demo
  data:
    mongodb:
      port: 27017
      host: localhost
      username: admin
      password: password
      database: user_db
      auto-index-creation: true

grpc:
  port: 8085
  host: localhost